# -*- coding: utf-8 -*-
"""CSE303_Lab_02_Tasks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iAa2rw9-9pKG-eOTu9YHWM-SGe-BJWCi
"""

#Task 01
import pandas as pd
data = pd.read_csv("iris.csv") #read the file
data

for index, row in data.iterrows():
  if row["sepal.length"] >= 4.2:
    print(row)

# Task 03
data["width"] = data["sepal.width"] + data["petal.width"]
data

column = ["petal.length", "petal.width"]
data[column].describe()

#Task 05
something = 87%75
data.iloc[0:something]