# -*- coding: utf-8 -*-
"""CSE303_Lab_2_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxdAuglZ5tXEFr9nbxQxcBqJAh3pzXu7

# **Pandas Introduction**
# What is Pandas?

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

\

# Why Use Pandas?
Pandas allows us to analyze big data and make conclusions based on statistical theories.

Pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.

\

# What Can Pandas Do?
Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?
What is average value?
Max value?
Min value?
Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

\

**Where is the Pandas Codebase?**

The source code for Pandas is located at this github repository https://github.com/pandas-dev/pandas

**Import Pandas**

Once Pandas is installed, import it in your applications by adding the import keyword:
"""

import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

"""**Pandas as pd**

Pandas is usually imported under the pd alias.

alias: In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:
"""

import pandas as pd

# Now the Pandas package can be referred to as pd instead of pandas.


import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

"""**Pandas Series**

**What is a Series?**

A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.
"""

# Create a simple Pandas Series from a list:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

"""**Labels**

If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.
"""

# Return the first value of the Series:

print(myvar[0])

"""**Create Labels**

With the index argument, you can name your own labels.
"""

# Create your own labels:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

"""When you have created labels, you can access an item by referring to the label.

"""

# Return the value of "y":

print(myvar["y"])

# Create your own labels for this 2d array:

import pandas as pd

arr = [[1, 2, 3], [4, 5, 6]]

# Code Here
row = ['row1', 'row2']
colm = ['col1', 'col2', 'col3']

df = pd.DataFrame(arr, index=row, columns=colm)

print(df)

# Return the value 5:

# Code Here
val_five = df.loc['row2', 'col2']
print(val_five)

"""**Key/Value Objects as Series**

You can also use a key/value object, like a dictionary, when creating a Series.
"""

# Create a simple Pandas Series from a dictionary:

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

"""Note: The keys of the dictionary become the labels.

To select only some of the items in the dictionary, use the index argument and specify only the items you want to include in the Series.
"""

# Create a Series using only data from "day1" and "day2":

import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

# Create a Series using only data from "b":

import pandas as pd

calories = {"a": 12, "b": 31, "c": 24}

# Code Here
myvar = pd.Series(calories["b"], index=["b"])

print(myvar)

"""**DataFrames**

Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.
"""

# Create a DataFrame from two Series:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

"""**What is a DataFrame?**

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
"""

# Create a simple Pandas DataFrame:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

"""**Locate Row**

As you can see from the result above, the DataFrame is like a table with rows and columns.

Pandas use the loc attribute to return one or more specified row(s)
"""

# Return row 0:

#refer to the row index:
print(df.loc[0])

# Return row 0 and 1:

#use a list of indexes:
print(df.loc[[0, 1]])

# Return row 1 and 2:

#use a list of indexes:

# Code Here
print(df.loc[[1, 2]])

"""**Named Indexes**

With the index argument, you can name your own indexes.
"""

# Add a list of names to give each row a name:

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

# Add a list of names to give each row a name:

import pandas as pd

data1 = {
  "a": [3, 6, 9, 12],
  "b": [2, 4, 6, 8],
  "c": [10, 20, 30, 50]
}

# Code Here

df1 = pd.DataFrame(data1, index = ["row1", "row2", "row3", "row4"])

print(df1)

"""**Locate Named Indexes**

Use the named index in the loc attribute to return the specified row(s).
"""

# Return "day2":

# refer to the named index:
print(df.loc["day2"])

# Return a row from df1:

# refer to the named index:

# Code Here
print(df1.loc["row1"])

"""**Pandas Read CSV**

**Read CSV Files**

A simple way to store big data sets is to use CSV files (comma separated files).

CSV files contains plain text and is a well know format that can be read by everyone including Pandas.

In our examples we will be using a CSV file called 'data.csv'.
"""

# Load the CSV into a DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

# Load the "forestfires.csv" into a DataFrame:

# Code Here

import pandas as pd

df1 = pd.read_csv('forestfires.csv')

print(df1.to_string())

"""use to_string() to print the entire DataFrame.

If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows:

"""

# Print the data DataFrame without the to_string() method:

import pandas as pd

print(df)

# Print the "forestfires" DataFrame without the to_string() method:

# Code Here
import pandas as pd
print(df1)

"""max_rows
The number of rows returned is defined in Pandas option settings.

You can check your system's maximum rows with the pd.options.display.max_rows statement.
"""

# Check the number of maximum returned rows:

import pandas as pd

print(pd.options.display.max_rows)

"""In my system the number is 60, which means that if the DataFrame contains more than 60 rows, the print(df) statement will return only the headers and the first and last 5 rows.

You can change the maximum rows number with the same statement.
"""

# Increase the maximum number of rows to display the entire data DataFrame:

import pandas as pd

pd.options.display.max_rows = 9999

print(df)

# Increase the maximum number of rows to display the entire forestfires DataFrame:

# Code Here
import pandas as pd
pd.options.display.max_rows = 9999
print(df1)

"""**Pandas - Analyzing DataFrames**

**Viewing the Data**

One of the most used method for getting a quick overview of the DataFrame, is the head() method.

The head() method returns the headers and a specified number of rows, starting from the top.
"""

# Get a quick overview by printing the first 10 rows of the data DataFrame:

import pandas as pd

print(df.head(10))

# Get a quick overview by printing the first 10 rows of the forestfires DataFrame:

# Code Here
import pandas as pd
print(df1.head(10))

# Print the first 5 rows of the data DataFrame:

import pandas as pd

print(df.head())

# Print the first 5 rows of the forestfires DataFrame:

# Code Here

"""There is also a tail() method for viewing the last rows of the DataFrame.

The tail() method returns the headers and a specified number of rows, starting from the bottom.
"""

# Print the last 5 rows of the data DataFrame:

print(df.tail())

# Print the last 5 rows of the forestfires DataFrame:

# Code Here
import pandas as pd

print(df1.head())

"""**Info About the Data**

The DataFrames object has a method called info(), that gives you more information about the data set.
"""

# Print information about the data:

print(df.info())

"""The result tells us there are 169 rows and 4 columns:

And the name of each column, with the data type:

\

**Null Values**

The info() method also tells us how many Non-Null values there are present in each column, and in our data set it seems like there are 164 of 169 Non-Null values in the "Calories" column.

Which means that there are 5 rows with no value at all, in the "Calories" column, for whatever reason.

Empty values, or Null values, can be bad when analyzing data, and you should consider removing rows with empty values. This is a step towards what is called cleaning data, and you will learn more about that in the next chapters.
"""

# Print information about the forestfires:

# Code Here
print(df1.tail())

"""\
**Pandas - Cleaning Data**

**Data Cleaning**

Data cleaning means fixing bad data in your data set.

Bad data could be:

Empty cells
Data in wrong format
Wrong data
Duplicates

**Pandas - Cleaning Empty Cells**

**Empty Cells**

Empty cells can potentially give you a wrong result when you analyze data.

**Remove Rows**

One way to deal with empty cells is to remove rows that contain empty cells.

This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.
"""

# Return a new Data Frame with no empty cells:

import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna()

print(new_df.to_string())

# Return a forestfires new Data Frame with no empty cells:

# Code Here
print(df1.info())

"""Note: By default, the dropna() method returns a new DataFrame, and will not change the original.

If you want to change the original DataFrame, use the inplace = True argument:
"""

# Remove all rows with NULL values:

import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(inplace = True)

print(df.to_string())

# Remove all rows with NULL values (forestfires.csv):

import pandas as pd

forestfires = pd.read_csv('forestfires.csv')

# Code Here

"""Note: Now, the dropna(inplace = True) will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

\

**Replace Empty Values**

Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value:
"""

# Replace NULL values with the number 130:

import pandas as pd

df = pd.read_csv('data.csv')

df.fillna(130, inplace = True)

df

# Replace NULL values with the number 74 (forestfires.csv):

# Code Here

"""**Replace Only For Specified Columns**

The example above replaces all empty cells in the whole Data Frame.

To only replace empty values for one column, specify the column name for the DataFrame:
"""

# Replace NULL values in the "Calories" columns with the number 130:

import pandas as pd

df = pd.read_csv('data.csv')

df["Calories"].fillna(130, inplace = True)

df

# Replace NULL values in the (forestfires.csv) "temp" columns with the number 18:

# Code Here

"""**Replace Using Mean, Median, or Mode**

A common way to replace empty cells, is to calculate the mean, median or mode value of the column.

Pandas uses the mean() median() and mode() methods to calculate the respective values for a specified column:
"""

# Calculate the MEAN, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mean()

df["Calories"].fillna(x, inplace = True)

df

# Calculate the MEAN, and replace any empty values with it (forestfires) "temp" columns:

# Code Here

"""Mean = the average value (the sum of all values divided by number of values)."""

# Calculate the MEDIAN, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].median()

df["Calories"].fillna(x, inplace = True)

df

# Calculate the MEDIAN, and replace any empty values with it (forestfires) "temp" columns:

# Code Here

"""Median = the value in the middle, after you have sorted all values ascending."""

# Calculate the MODE, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)

df

# Calculate the MODE, and replace any empty values with it (forestfires) "temp" columns:

# Code Here

"""Mode = the value that appears most frequently.

\
**Pandas - Cleaning Data of Wrong Format**

**Data of Wrong Format**

Cells with data of wrong format can make it difficult, or even impossible, to analyze data.

To fix it, you have two options: remove the rows, or convert all cells in the columns into the same format.

**Convert Into a Correct Format**

In our Data Frame, we have two cells with the wrong format. Check out row 22 and 26, the 'Date' column should be a string that represents a date:

Let's try to convert all cells in the 'Date' column into dates.

Pandas has a to_datetime() method for this:

We will use 'data_Date.csv' dataset.
"""

import pandas as pd

df = pd.read_csv('data_Date.csv')
df

# Convert to date:

import pandas as pd

df = pd.read_csv('data_Date.csv')

df['Date'] = pd.to_datetime(df['Date'])

print(df.to_string())

"""As you can see from the result, the date in row 26 was fixed, but the empty date in row 22 got a NaT (Not a Time) value, in other words an empty value. One way to deal with empty values is simply removing the entire row.

\

Removing Rows
The result from the converting in the example above gave us a NaT value, which can be handled as a NULL value, and we can remove the row by using the dropna() method.
"""

# Remove rows with a NULL value in the "Date" column:

df.dropna(subset=['Date'], inplace = True)

df

"""**Pandas - Fixing Wrong Data**

**Wrong Data**

"Wrong data" does not have to be "empty cells" or "wrong format", it can just be wrong, like if someone registered "199" instead of "1.99".

Sometimes you can spot wrong data by looking at the data set, because you have an expectation of what it should be.

If you take a look at our data set, you can see that in row 7, the duration is 450, but for all the other rows the duration is between 30 and 60.

It doesn't have to be wrong, but taking in consideration that this is the data set of someone's workout sessions, we conclude with the fact that this person did not work out in 450 minutes.

How can we fix wrong values, like the one for "Duration" in row 7?

**Replacing Values**

One way to fix wrong values is to replace them with something else.

In our example, it is most likely a typo, and the value should be "45" instead of "450", and we could just insert "45" in row 7:
"""

# Set "Duration" = 45 in row 7:

df.loc[7, 'Duration'] = 45

df

# Set "Duration" = 55 in row 17 and 20:

# Code Here

"""For small data sets you might be able to replace the wrong data one by one, but not for big data sets.

To replace wrong data for larger data sets you can create some rules, e.g. set some boundaries for legal values, and replace any values that are outside of the boundaries.
"""

# Loop through all values in the "Duration" column.

# If the value is higher than 120, set it to 120:

# Code Here

"""**Removing Rows**

Another way of handling wrong data is to remove the rows that contains wrong data.

This way you do not have to find out what to replace them with, and there is a good chance you do not need them to do your analyses.
"""

# Delete rows where "Duration" is higher than 120:

# Code Here

"""**Pandas - Removing Duplicates**

**Discovering Duplicates**

Duplicate rows are rows that have been registered more than one time.

\

By taking a look at our test data set, we can assume that row 11 and 12 are duplicates.

To discover duplicates, we can use the duplicated() method.

The duplicated() method returns a Boolean values for each row:
"""

# Returns True for every row that is a duplicate, othwerwise False:

print(df.duplicated())

# Returns True for every row that is a duplicate, othwerwise False (forestfires.csv):

# Code Here

"""**Removing Duplicates**

To remove duplicates, use the drop_duplicates() method.
"""

# Remove all duplicates:

df.drop_duplicates(inplace = True)

df

# Remove all duplicates (forestfires.csv):

# Code Here

"""**Pandas - Data Correlations**

Finding Relationships
A great aspect of the Pandas module is the corr() method.

The corr() method calculates the relationship between each column in your data set.

The examples uses a CSV file called: 'data.csv'.
"""

# Show the relationship between the columns:

import pandas as pd

df = pd.read_csv('data.csv')

df.corr()

"""Note: The corr() method ignores "not numeric" columns.

**Result Explained**

The Result of the corr() method is a table with a lot of numbers that represents how well the relationship is between two columns.

The number varies from -1 to 1.

1 means that there is a 1 to 1 relationship (a perfect correlation), and for this data set, each time a value went up in the first column, the other one went up as well.

0.9 is also a good relationship, and if you increase one value, the other will probably increase as well.

-0.9 would be just as good relationship as 0.9, but if you increase one value, the other will probably go down.

0.2 means NOT a good relationship, meaning that if one value goes up does not mean that the other will.

\

**What is a good correlation?**

 It depends on the use, but I think it is safe to say you have to have at least 0.6 (or -0.6) to call it a good correlation.

**Perfect Correlation:**

We can see that "Duration" and "Duration" got the number 1.000000, which makes sense, each column always has a perfect relationship with itself.

**Good Correlation:**

"Duration" and "Calories" got a 0.922721 correlation, which is a very good correlation, and we can predict that the longer you work out, the more calories you burn, and the other way around: if you burned a lot of calories, you probably had a long work out.

**Bad Correlation:**

"Duration" and "Maxpulse" got a 0.009403 correlation, which is a very bad correlation, meaning that we can not predict the max pulse by just looking at the duration of the work out, and vice versa.
"""

# Show the relationship between the columns (forestfires.csv):

# Code Here