# -*- coding: utf-8 -*-
"""Lab_09_Linear_Regression_on_Exam_Score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXlHJ6UBvO_oRzEvYgP45Y-ybqBB3zhy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_csv("test_scores.csv")
df

for column in df.columns:
  if( df[column].dtype == "object"):
    grp1 = LabelEncoder()
    grp1.fit( df[column] )
    df[column] = grp1.transform( df[column])
df

X = df[['pretest']]
y = df['posttest']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train,y_train)

y_prediction = model.predict(X_test)

print(mean_squared_error(y_test, y_prediction))